### PR TITLE
adding IBEAM cursor to selectable cursors in Windows

### PR DESCRIPTION
**Pull request by dcnieho**
needed this, am building a selectable textbox for user input ;)
Untested as I don't have a build setup for psychtoolbox, but IDC_IBEAM is as found here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms648391(v=vs.85).aspx

### CODE REVIEW

**Comment by kleinerm** [comment]
Looks good, apart from the "// No cursor:" comment. I just checked and with your commit, all OS'es will support IBeam, each with a different cursorId though: Windows = 8, Linux = 1, OSX = 4.
Maybe would make sense to define a new common name 'TextCursor' or 'IBeam' for this and add mapping from name to os-specific id to ShowCursor.m to simplify things?

**Comment by dcnieho** [comment]
Ah crap, carelessly copied without even checking what the comment said. Yes, makes sense to have an IBeam by string. I think 'TextCursor' is the better, more understandable name, I'll just put "AKA, IBeam" or so in the docs as well.

**Comment by dcnieho** [comment]
Fixed up and extended as discussed ;)

**Comment by kleinerm** [comment]
Diederick, the Screen.mexw64 in my kleinerm/Psychtoolbox-3 repo is now updated to support this, if you want to try.

**Comment by dcnieho** [comment]
Thanks! Just got back to computer where this was running. All works fine :)

**Pull request merged**
