### PR TITLE
Kb updates

### PR DESCRIPTION
**Pull request by dcnieho**
small formatting changes to KbWait, and doc corrections to KbQueueFlush. Major: KbQueueWait gained forWhat and untilTime. See commit text for details

### CODE REVIEW

**Comment by kleinerm** [comment]
The first two commits are fine. But for the 3rd one i'd like to have test/demo code added to KbQueueDemo so we have a demo and a test case for this being used/working correctly. It's one of the demos i always run whenever anything touched the input handling, or when testing new operating system releases.

The inverted recommendation for KbQueueFlush is a problem for 'forWhat=0', you can't do that, it is a drastic regression in backwards compatibility. It could trip up existing code if users upgrade their PTB and actually followed the KbQueueFlush recommendation.

It is fine to demand the different use of KbQueueFlush for forWhat > 0 as that is new functionality that can't break existing code, but for the default case you need to come up with a special case.

So this pull will have to wait for the next release cycle.

**Comment by dcnieho** [comment]
Thanks for reviewing. I'll add an extra case to KbQueueDemo, exercising all forWhat options of KbQueueWait.

Note that any old KbQueueWait call will work exactly the same as before. The default 0 argument is the mode it operated in before, and if KbQueueFlush is called before, it will have the same effect. It is only when writing new code that the user should now reconsider whether to clear the queue. Operation of the function will be more robust if you don't. In short, my changes are fully backwards compatible if the user does not change their code (I've verified this with tests when implementing this function), no special case is needed. I would not suggest advertising the changed KbQueueFlush recommendation in the release notes as this is indeed not a change to be made haphazardly.

Should i change the help to add something like "NB. Previously, use of KbQueueFlush before calling this function was recommended. While the current function maintains backwards compatibility for this use case, any changes of existing code to follow the new recommendation and remove preceding KbQueueFlush calls should be carefully considered and tested (don't change what works)."

**Comment by kleinerm** [comment]
Ah ok, so i misunderstood the commit message. Ja, add some bit to the help text to explain the change in KbQueueFlush recommendations as you suggested.

**Comment by dcnieho** [comment]
ok, added the help. Good to go then (before or after current release is your choice :))

**Comment by kleinerm** [comment]
Will test it later, haven't reviewed the actual KbQueueWait code in every detail, just skimmed it.
Thanks.

**Pull request merged**
