### PR TITLE
Improve KbQueue's cooked key for MS-Windows

### PR DESCRIPTION
**Pull request by dcnieho**
when computing cookedKey through ToAsciiEx:
- modifier press state is passed now, such that, e.g., Alt-Gr modifier works
- caps lock state is passed so thats taken into account
- when a dead char is in the keyboard buffer and a subsequent character is typed that does not combine with it, we now return the last typed character instead of nothing.

Also, now documenting all possible return values from ToAsciiEx (including -1 which is not in the docs) and having some debug code to simplify further work on this function.

Solves issue #373

### CODE REVIEW

**Comment by dcnieho** [comment]
One discussion point: when a dead char is typed and a subsequent char that does not combine with it, ToAsciiEx puts the dead char in the lowest byte and the last typed char in the second byte. So this would return a value like (¨+$) 168+36>>8=9384. It fits in the return type, and is unambiguously understood (there are two chars when cookedKey>255), but i am not sure returning that would be a backwards compatibility hazard. char(9384) does funky things of course.
Can we just return this? Can we add an optional state for PsychHID enabling this? I'd love to have it for a text input box that i am building.

**Comment by kleinerm** [comment]
Merging this for testing. I will cleanup that awful mess of indentation and white-space errors in that file after the merge, so make sure to not base further work on the non-cleaned version.

**Comment by kleinerm** [comment]
Wrt. to merging dead chars, i don't think that is a good idea. It's also important that it behaves the same or as similar as possible on the different OS'es, or people will start to rely on non-portable behaviours, write corresponding scripts, and then complain if things break. E.g., i'd rather not have composition work than have it work on only some subset of OS'es.

**Comment by dcnieho** [comment]
Thanks for looking at it further. I guess i am not using an editor that picks up on how whitespace is formatted, but always inserts spaces. Sorry for that.

Re merging of/composing with dead chars: This always worked on MSWIN. The only new thing beside adding all those shift states is handling the case where nChar==2, when merging of deadchar with typed character (e.g. adding a diacritic) failed because they are not composable. Instead of returning 0 for cookedKey, it now returns the last typed key. My question above was about introducing an option to return both keys by shifting one of them to another bit in the int.

Thanks!

**Comment by kleinerm** [comment]
Oh the white-space mess isn't caused by you. Many files have chaos, because i had to switch between half a dozen machines and different text editors, sometimes as pathetic as Notepad, with different settings in the past, as i never had dedicated machines for PTB development - i still don't have any apart from my laptop. Also many editors don't show tabs and white-space, or dangling white-space at the end of lines. Matlab and Apples XCode are pretty horrible at spewing white-space all over the place. At least for Linux devel i can boot most machine from a portable USB drive, so now i can get consistent formatting most of the time.

I usually clean up source files in a separate commit before i make large modifications, so white-space fixups are separate from semantic change. For reference, the preferred format for the C code is UNIX line endings, no tabs, all indentations with spaces, and a indentation width of 4 spaces. For Matlab it is no tabs, and probably for convenience adapt to whatever indentation a file already has, as we are not consistent there either - sometimes 2 space indents, sometimes 4 space.

**Pull request merged**
