### PR TITLE
Fix compilation on macOS arm64

### LINKED ISSUE #587: Q: Wheels for Python?
I used to use PTB on MATLAB some years ago (10?) but since then moved to Python. I just heard that PTB has made some progress in Python, but the PyPi releases appear to be source ones (at least `pip install psychtoolbox` on my macOS machine does a source install). cc @peircej since I think you're mentioned as working on this?

If it would be helpful, I'm happy to set up automated PyPi wheel builds for macOS, Linux, and Windows using [cibuildwheel](https://github.com/joerick/cibuildwheel). I've done it for [VisPy](https://github.com/vispy/vispy/pull/1663) and more recently [python-rtmixer](https://github.com/spatialaudio/python-rtmixer/pull/16). All in all it's pretty painless, but there are a bunch of steps (setting up Azure pipelines is the most annoying part). Having done it recently, though, I'm familiar with the required steps so can walk someone through what a repo owner/maintainer has to do.

### PR DESCRIPTION
**Pull request by larsoner**
Toward https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/587 

- [x] Treat linker warnings as errors on macOS
- [ ] Add `.a` file for arm64 (I need help with this!)
- [ ] Get it to build locally
- [ ] Add ~~[cirrus-ci](https://cirrus-ci.com/)~~ GHA macos-14 build to actually test it in CIs ~~(someone with admin permissions needs to enable this then I can create a `.yaml`)~~
- [ ] Triage build based on `platform.machine` (or better, command-line arg or something else???)
- [ ] Set up env vars so that `platform.machine()` can be overridden (e.g., in cross-compilation settings / cibuildwheel)

@kleinerm are there macOS arm64 `.a` files that can be added? That's the next step I think, but I don't know how those were generated in the first place. I do have access to arm64 hardware if you can point me to some args on how PortAudio or whatever needs to be built to produce suitable `.a` files.

On this PR so far I get a (correct) error now that it can't link properly:
```
$ python setup.py build
...
clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/larsoner/opt/miniconda3/envs/mne/lib -L/Users/larsoner/opt/miniconda3/envs/mne/lib -Wl,-rpath,/Users/larsoner/opt/miniconda3/envs/mne/lib -L/Users/larsoner/opt/miniconda3/envs/mne/lib -framework Carbon -framework CoreAudio -I/opt/OpenBLAS/include -I/opt/homebrew/opt/llvm/include build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/MODULEVersion.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/MiniBox.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/ProjectTable.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychAuthors.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychCellGlue.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychError.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychHelp.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychInit.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychInstrument.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychMemory.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychRegisterProject.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychScriptingGlue.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychScriptingGlueMatlab.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychStructGlue.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/Base/PsychVersioning.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/Common/PsychPortAudio/RegisterProject.o build/temp.macosx-11.0-arm64-cpython-310/./PsychSourceGL/Source/OSX/Base/PsychTimeGlue.o build/temp.macosx-11.0-arm64-cpython-310/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.o PsychSourceGL/Cohorts/PortAudio/libportaudio_osx_64.a -o build/lib.macosx-11.0-arm64-cpython-310/psychtoolbox/PsychPortAudio.cpython-310-darwin.so -Wl,-fatal_warnings
ld: warning: ignoring file PsychSourceGL/Cohorts/PortAudio/libportaudio_osx_64.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: fatal warning(s) induced error (-fatal_warnings)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
```

Closes #587

### CODE REVIEW

**Comment by larsoner** [comment]
Oh, there are no CIs set up here it seems. So maybe the `cirrus-ci` step is overkill.

Happy to add some quick Linux, Windows, and macOS `python setup.py install` tests using GitHub actions if it would help

**Comment by dcnieho** [comment]
I think the relevant source and a make file are in
https://github.com/Psychtoolbox-3/Psychtoolbox-3/tree/master/PsychSourceGL/Cohorts/PortAudio

I have never touched that. Maybe you can make something of that?

**Comment by larsoner** [comment]
Based on a very quick `blame` there is this commit which has some hints:

https://github.com/Psychtoolbox-3/Psychtoolbox-3/commit/d87932b191dfab93abf6f7ac7483723b8ca993ac

**Comment by larsoner** [comment]
Maybe this is more doable nowadays that macos-14 is an arm64 runner on GitHub actions for example. At least for `python-rtmixer` we were able to build portaudio, not sure how well it worked (didn't test it much!). So this seems more tenable from a technological standpoint at least.

**Comment by kleinerm** [comment]
Active work to make this work on Apple Silicon is underway. But as Psychtoolbox is badly underfunded and always tethering on the verge of bankruptcy and catastrophic project failure, thanks to the almost complete lack of financial support of our users, including all the Python users who could have supported us by buying paid support memberships, we will turn macOS support into a paid-only option for future releases. Iow. the solution technically mostly exist already, but I can't release anything until we've setup a suitable subscription model and licensing mechanism. All voluntary funding models we've tried in the last 5+ years have failed, so we are at the point where we have to put away the carrot and get out the stick. Sad but true. See https://youtu.be/05gpkP_EMoc

**Comment by larsoner** [comment]
Fair enough, I'll close this then!

**Comment by peircej** [comment]
@kleinerm I did email to discuss this, back in May, but haven't heard back. Maybe it got swallowed in the ether. I'll try again. But, for sure, I'm open to discussing how we can help again with financing

**Pull request closed without merging**
