### PR TITLE
enhanced SortCell, adding UniqueCell

### PR DESCRIPTION
**Pull request by dcnieho**

### CODE REVIEW

**Comment by kleinerm** [comment]
Apart from a small indentation glitch in SortCell.m this is fine. However, it uses ~ for return argument suppression, which is not supported on Octave 3.2 and at least according to our web page we still support that - not tested since many years. Maybe better to pull this after a final 3.0.12 release and then simply drop support for Octave < 3.8. I also don't know which Matlab version introduced ~.

**Comment by dcnieho** [comment]
I've fixed the spacing, turns out there were a few tabs in the file. ~ was introduced in R2009b (I just checked), so no problem there.
Is there any reason to keep supporting Octave 3 instead of 4? Since its free, it might make sense to not support too far down, especially if its more building and testing work.
Sounds good to wait till after the last 3.0.12 release. After that, I'll also make a pull request to clean up some internals (such as use of psychassert in our own function, it was introduced in R2007a!). of course our wrapper functions will remain, just internal use can be cleaned up (e.g., for assert, that would lead to cleaner error messages that are thrown from the location or the error, not deeper in the call stack).

**Comment by kleinerm** [comment]
Ok, so Octave 3.8+ and R2012a would be covered for ~. Octave 3.8 and R2012a is what i currently use for building and most of the testing.

I'll keep Octave 3.8 supported on Linux because that is what ships by default in Ubuntu 14.04-LTS. As LTS stands for "Long term support" and 14.04 LTS has 3 years more lifetime i don't want to force all 14.04 users to upgrade to 16.04 LTS in a haste, or suffer inconvenience when using Octave, although an upgrade to 16.04 is advantageous for performance and functionality. Also on Linux Octave 3+4 are supported by the same mex files from us, or by individually compiled mex files from NeuroDebian, so supporting 3 and 4 is essentially free for me. Only a bit of care must be taken not breaking existing M-Files.

On Windows we only do the latest 64-Bit Octave 4 for sanity once 3.0.12 ends, probably within a month. On OSX i'll cancel Octave-3 support after 3.0.12, as supporting it is extra effort and uses extra space in our git repo.

**Comment by dcnieho** [comment]
Sounds great. I agree with your reasoning, and think you're making a good
compromise between lean and rich support.

**Comment by dcnieho** [comment]
NB: I've rebased this on top of your own master. as that is not in PTB yet, be careful with the order in which you merge things in for 3.0.13

**Comment by kleinerm** [comment]
Ok, i merged this manually into my master by cherry picking the 3 commits. Merging all this rebased stuff is too likely to cause merge conflicts. Better don't rebase in the future, but create a feature branch for stuff in a pull request.

I also fixed up line endings in separate commits to be UNIX style, not Windows/DOS style.

Thanks.

**Comment by dcnieho** [comment]
Hi Mario,

Cool, will do the feature branch next time. I'm never quite sure what
core.autocrlf setting to use. Its set to true now.
Ah, but i see all line ending normalization is switched of by the
.gitattributes in the repo root. Should we perhaps change that?

Cheers,
Dee

**Pull request closed without merging**
