### PR TITLE
Create XYZToDKL

### PR DESCRIPTION
**Pull request by da5nsy**

### CODE REVIEW

**Comment by kleinerm** [comment]
This is marked a draft, so unfinished?

It needs more error checking, and more extensive help texts about usage/syntax, what it does etc.
Cfe. XYZToLuv.m

**Comment by da5nsy** [comment]
> This is marked a draft, so unfinished?

Yep - I want to double-check some things before I submit properly.

> It needs more error checking, and more extensive help texts about usage/syntax, what it does etc.

Agreed.

> Cfe. XYZToLuv.m

What does Cfe. stand for in this context?

**Comment by kleinerm** [comment]
Cfe = "See for example", afaik ;).

**Comment by kleinerm** [comment]
No activity in a meaningful time period. Closing this for now. Reopen it when it is ready.

**Pull request closed without merging**
