### PR TITLE
Rect enhancement again

### PR DESCRIPTION
**Pull request by dcnieho**
All functions can now deal with 4xM rect arrays as well, fixing the issues with the demos. Extended unit tests, and ran all demos to verify things work correctly (on Windows).
Issue #260

### CODE REVIEW

**Comment by dcnieho** [comment]
Do you think this is mergable now @kleinerm?

**Comment by kleinerm** [comment]
Your pull request seems to contain all changes twice now? Or what is that "All previously vectorized..." commit apart from "Squash commit of all previous..."?

These rect changes make me nervous, there is a lot of potential for breaking existing code. If we don't notice breakage immediately and some user shows up half a year or year later with broken code then it would be hard to revert, and it would be our bug, not the users bug if his code worked before. I think we should go for the better-safe-than-sorry-route and make this opt-in. Add some optional flag to each rect function that if provided as 1 enables the new vectorization stuff, and if set to 0 or left out keeps the old behaviour. This way old code won't accidentally break. Then i'd like to have all the patches which change the stuff in PsychRects/ in one commit, so the whole thing can be easily reverted if something bad happens early after the beta release. And the remove duplicates stuff in one commit.

With converting the RectLeft et al. constants to numbers i'm not sure. Measuring this on Octave with a 5 year old Laptop it seems it only saves < 8 usecs. I'd imagine on Matlab and/or with a faster machine it would be even less. So i'm not sure if it is worth the loss in readability. Otoh its not a big deal either for the specific functions you changed it. In any case it would be a separate commit.

**Comment by dcnieho** [comment]
Thanks for looking at it again. I understand your nerves, very much. I am
not sure if the solution with the extra flag is somewhere where we should
want to go, it makes the code significantly more hairy and harder to
maintain. Perhaps it may be better to simply ignore this pull requests,
work wasted is better than trouble later.

Re the RectLeft etc constants: at one point (a while ago) i was profiling
and I hit against a more serious penalty of having these functions, with
matlab. It was weird indeed. Perhaps i should ascribe it to profiler
error/overhead.

There has been some cleanup and such as well as i went over these
functions. If you feel ignoring what is in here now is better, shall I put
only those in a new pull request?

Cheers!

**Comment by kleinerm** [comment]
Throwing away work wouldn't be nice if it has actual performance benefits. I think we can solve the problem then by simply creating new functions with the new behaviour. The existing rect functions won't change in syntax and semantic anyway. Simply create copies of the old functions, maybe with a 'v' added to the end for "fully vectorized", e.g., CenterRectOnPointv and CenterRectOnPointdv. That way you don't need to maintain extra optional flags, nobody will accidentally use the new functions with code that isn't prepared for them and new code can be written with the fully vectorized versions.

How did you test RectLeft? Singe invocations could give longer times because the first invocation will have to load the file from disc, but if you test it in a tic-toc for loop of 1 million iterations and leave out the first invocations then at least i ended with the 8 usecs on old hardware. Actually just retesting, Matlab R2012a does the same in 0.5 usecs, probably thanks to its JIT compiler for optimizing for-loops. So i think this is not really an issue.

**Comment by denispelli** [comment]
An extension is fine, but please maintain consistent rule of
capitalization. Since every word begins with a capital the suffix V should
be capitalized as well.
Ok?
Best
Denis

On Sunday, September 13, 2015, Mario Kleiner <notifications@github.com>
wrote:

> Throwing away work wouldn't be nice if it has actual performance benefits.
> I think we can solve the problem then by simply creating new functions with
> the new behaviour. The existing rect functions won't change in syntax and
> semantic anyway. Simply create copies of the old functions, maybe with a
> 'v' added to the end for "fully vectorized", e.g., CenterRectOnPointv and
> CenterRectOnPointdv. That way you don't need to maintain extra optional
> flags, nobody will accidentally use the new functions with code that isn't
> prepared for them and new code can be written with the fully vectorized
> versions.
>
> How did you test RectLeft? Singe invocations could give longer times
> because the first invocation will have to load the file from disc, but if
> you test it in a tic-toc for loop of 1 million iterations and leave out the
> first invocations then at least i ended with the 8 usecs on old hardware.
> Actually just retesting, Matlab R2012a does the same in 0.5 usecs, probably
> thanks to its JIT compiler for optimizing for-loops. So i think this is not
> really an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/264#issuecomment-139901029>
> .
>


-- 
Denis Pelli
Professor of Psychology and Neural Science at New York University
http://psych.nyu.edu/pelli/
http://denispelli.com
denis.pelli@nyu.edu

**Comment by kleinerm** [comment]
Closing this one, as it has gone stale.

**Pull request closed without merging**
