### PR TITLE
WiP  Travis: absorb installations into helper scripts, start fixing things up

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
@kleinerm apparently you didn't enable travis for Psychtoolbox-3/Psychtoolbox-3 repo, so no tests are ran for PRs... please do -- we will fix it all up, no worries

**Comment by kleinerm** [comment]
Ok, pulled your PR's, and i think i enabled travis on the official repo now.

**Comment by yarikoptic** [comment]
oh, you were too fast @kleinerm  ;)  it wasn't yet fully cooked (thus I had 'WiP' prefix to signal Work in Progress):  I must say that original travis setup was a complete "fake" and should have not been merged until fixed up ;-)

Not biggie though -- I can reissue a new PR and let's see if travis would pick it up correctly.  The point of using CI is that a PR must not be merged until "tests pass".

**Comment by kleinerm** [comment]
Ok, no further pulls from you until you give green light. Did you get the failure notice as well as author of the PR?

**Pull request merged**
